# -*- mode: ruby -*-
# vi: set ft=ruby :
 
 Vagrant.configure("2") do |config|
   config.vm.box = "bento/ubuntu-22.04"
 
   config.vm.network "private_network", type: "dhcp"
 
   config.vm.provision "file", source: "./", destination: "./"
 
   config.vm.define "dbserver", primary: false do |dbserver|
     dbserver.vm.network "forwarded_port", guest: 5432, host: 1234
     dbserver.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
     end
     dbserver.vm.hostname = "dbserver"
     dbserver.vm.provision "shell", privileged: true, inline: <<-SHELL
      cd /home/vagrant/Chirp-Project
      # Ensure scripts have correct permissions
      chmod +x install-postgresql.sh
      # Fix potential Windows line endings
      sed -i 's/\\r$//' install-postgresql.sh
      ./install-postgresql.sh
    SHELL
   end
     
   config.vm.define "itu-minitwit", primary: true do |server|
     server.vm.network "forwarded_port", guest: 8080, host: 8080
     server.vm.network "forwarded_port", guest: 3000, host: 3000
     server.vm.network "forwarded_port", guest: 9090, host: 9090
     server.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
     end
     server.vm.hostname = "itu-minitwit"
     server.vm.provision "shell", inline: 'echo "export DOCKER_USERNAME=' + "'" + ENV["DOCKER_USERNAME"] + "'" + '" >> ~/.bash_profile'
     server.vm.provision "shell", inline: 'echo "export DOCKER_ACCESS_TOKEN=' + "'" + ENV["DOCKER_ACCESS_TOKEN"] + "'" + '" >> ~/.bash_profile'
     server.vm.provision "shell", privileged: true, inline: <<-<<-SHELL
      # Fix line endings for scripts
      cd /home/vagrant/Chirp-Project
      chmod +x docker-cli.sh deploy.sh
      sed -i 's/\\r$//' docker-cli.sh deploy.sh

      # Source bash profile
      source /home/vagrant/.bash_profile

      # Run Docker installation and deployment
      ./docker-cli.sh
      ./deploy.sh
    SHELL
   end
 end