# -*- mode: ruby -*-
# vi: set ft=ruby :

$ip_file = "db_ip.txt"

Vagrant.configure("2") do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.define "dbserver", primary: false do |dbserver|
    dbserver.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = ENV["SSH_KEY_NAME"]
      provider.token = ENV["DIGITAL_OCEAN_TOKEN"]
      provider.image = 'ubuntu-22-04-x64'
      provider.region = 'fra1'
      provider.size = 's-1vcpu-1gb'
      provider.privatenetworking = true
     end
 
    dbserver.vm.hostname = "dbserver"
    
    server.trigger.after :up do |trigger|
      trigger.info =  "Writing dbserver's IP to file..."
      trigger.ruby do |env,machine|
        remote_ip = machine.instance_variable_get(:@communicator).instance_variable_get(:@connection_ssh_info)[:host]
        File.write($ip_file, remote_ip)
      end
    end
   
   server.vm.provision "shell", inline: <<-SHELL
         # The following addresses an issue in DO's Ubuntu images, which still contain a lock file
         sudo fuser -vk -TERM /var/lib/apt/lists/lock
         sudo apt-get update
         
         cd ../vagrant
         chmod +x docker-cli.sh
         ./docker-cli.sh
   
         cd database
         docker compose up --build -d
       SHELL
     end

  config.vm.define "itu_minitwit", primary: true do |server|
    server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = ENV["SSH_KEY_NAME"]
      provider.token = ENV["DIGITAL_OCEAN_TOKEN"]
      provider.image = 'ubuntu-22-04-x64'
      provider.region = 'fra1'
      provider.size = 's-1vcpu-1gb'
      provider.privatenetworking = true
    end

    server.vm.hostname = "itu-minitwit"
    
    server.trigger.before :up do |trigger|
      trigger.info =  "Waiting to create server until dbserver's IP is available."
      trigger.ruby do |env,machine|
        ip_file = "db_ip.txt"
        while !File.file?($ip_file) do
          sleep(1)
        end
        db_ip = File.read($ip_file).strip()
        puts "Now, I have the dbserver's IP address: #{db_ip}"
      end
    end
    
    server.trigger.before :destroy do |trigger|
      trigger.info =  "Cleaning dbserver's IP file."
      trigger.ruby do |env,machine|
        File.delete($ip_file) if File.exist? $ip_file
      end
    end

    server.vm.provision "shell", inline: 'echo "export DB_SERVER_IP=' + "'" + File.read($ip_file).strip() + "'" + '" >> ~/.bash_profile'
    server.vm.provision "shell", inline: 'echo "export DOCKER_USERNAME=' + "'" + ENV["DOCKER_USERNAME"] + "'" + '" >> ~/.bash_profile'
    server.vm.provision "shell", inline: 'echo "export DOCKER_ACCESS_TOKEN=' + "'" + ENV["DOCKER_ACCESS_TOKEN"] + "'" + '" >> ~/.bash_profile'
    server.vm.provision "shell", inline: <<-SHELL
      # The following addresses an issue in DO's Ubuntu images, which still contain a lock file
      sudo fuser -vk -TERM /var/lib/apt/lists/lock
      sudo apt-get update
      
      # checks if "$HOME/.bashrc" is already inside "$HOME/.bash_profile" if not then append it the file into it
      if ! grep -q "$(cat $HOME/.bashrc)" $HOME/.bash_profile; then
        echo ". $HOME/.bashrc" >> $HOME/.bash_profile
      fi
      
      source $HOME/.bash_profile

      cd ../vagrant
      chmod +x deploy.sh
      chmod +x docker-cli.sh
      ./docker-cli.sh
      ./deploy.sh

      # docker build -t ${DOCKER_USERNAME}/itu-minitwit .
      # docker compose up -d
    SHELL
  end
end
