name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
    
      - name: Run Hadolint
        uses: hadolint/hadolint-action@0931ae097296863e5f188b8c6a0c5f9b95f79793  # v3.1.0
        with:
          dockerfile: ./Chirp-Project/Dockerfile

  shellcheck:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
        

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca  # master
        with:
          scandir: "."
          severity: warning 