name: Report

on:
  push:
    branches: ["main"]



jobs:
     build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v6
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v4
              with:
                root_file: main.tex
                working_directory: report
                args: -pdf -outdir=build -jobname=BSc_group_j -halt-on-error -file-line-error                
            - name: Debug Output
              run: find ./report -name "*.pdf"
            - name: Upload PDF file
              uses: actions/upload-artifact@v4
              with:
                        name: PDF
                        path: ./report/build/BSc_group_j.pdf
            - name: Commit PDF to repo
              run: |
                    git config user.name "github-actions"
                    git config user.email "github-actions@github.com"
                    git add ./report/build/BSc_group_j.pdf
                    git commit -m "Auto-generate PDF report"
                    git push
